### ISSUE TITLE
Add desktop/dock icon

### ISSUE THREAD

**Issue by HriBB** [Tomiyou/ivyterm#2]
I can get the icon in application launcher by placing the following into `~/.local/share/applications/ivyterm.desktop`
```desktop
[Desktop Entry]
Type=Application
Name=Ivyterm
Icon=/home/bojan/rust/ivyterm/target/release/ivyterm.png
Exec=/home/bojan/rust/ivyterm/target/release/ivyterm
Terminal=false
Categories=Development;
```
![image](https://github.com/user-attachments/assets/8809f5c9-2331-4e88-89c4-a70492ab38d1)

But not in the Gnome dock
![image](https://github.com/user-attachments/assets/c4ffbda5-505f-4d89-b472-b26544c0cb3f)

Also cannot "pin" the app into Gnome dock.

**Comment by Tomiyou** [comment]
Desktop icon was added some time ago.
